title: Nicholas Chitty
email: nicholas.chitty@gmail.com
description: >-
  William Nicholas Chitty, Software Engineer at Nelnet Payment Services. UCF graduate with expertise
  in Computer Science and Electrical Engineering, specializing in Verilog/VHDL, embedded software,
  and SaaS backend development. Passionate about solving complex problems through technology.
baseurl: ""
url: "https://chittyinsights.dev"

theme: jekyll-theme-chirpy
plugins:
  - jekyll-feed

github:
  username: NChitty

social:
  name: Nicholas Chitty
  email: nicholas.chitty@gmail.com
  links:
    # The first element serves as the copyright owner's link
    - https://github.com/NChitty
    - https://www.linkedin.com/in/nicholas-chitty/

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
