title: Nicholas Chitty
email: nicholas.chitty@gmail.com
description: >-
  William Nicholas Chitty, Software Engineer at Nelnet Payment Services. UCF graduate with expertise
  in Computer Science and Electrical Engineering, specializing in Verilog/VHDL, embedded software,
  and SaaS backend development. Passionate about solving complex problems through technology.
baseurl: ""
url: "https://chittyinsights.dev"
github_username: NChitty

theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
